config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'

  get '/search/:keyword', to: 'pages#search'

  #route for AJAX
  get '/search', to: 'pages#searchpage'
  post '/searchpost', to: 'pages#searchpost'

  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @batman = HTTParty.get("http://www.omdbapi.com/?s=Batman")
    logger.debug "HTTParty result is: #{@batman['Search']}"
    #code
  end

  def about
  end

  def search
    logger.debug "I am trying to search for #{params[:keyword]}"
    keyword = params[:keyword]
    @search = HTTParty.get("http://www.omdbapi.com/?s=#{keyword}")
    logger.debug "HTTParty result is: #{@keyword}"
  end

  def help
  end

  def searchpage
  end

  def searchpost
    logger.debug('got post')
    logger.debug( params[:q])
    keyword = params[:q]

    render json: {
      'result': keyword
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Httparty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home Page</h1>

<%= @batman %>

app/views/pages/search.html.erb
<h1>Search Results here</h1>


<ul>
  <% @search['Search'].each do |result| %>
  <li><%= result['Title'] %> <br />
      <%= image_tag result['Poster']%>
  </li>


  <% end %>
</ul>

app/views/pages/searchpage.html.erb
<h2>Ajax Search</h2>

<!-- remote true tells form to send an AJAX request -->
<div id="searchform">
  <%= form_tag searchpost_path, method: :post, remote: true do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag "Search" %>
  <% end %>
</div>